import type { ChannelState, Orchestra, StagePos } from "./core";
import { INSTRUMENT_MAP } from "./instruments";
import { mulberry32, hashString } from "./core";

/* ============================================================
   MAPA GLOBAL DE ESTILOS MUSICALES E INSTRUMENTACIÓN PRINCIPAL
   América · Europa · África · Asia · Europa del Este.
   Cada estilo incluye su tabla de parámetros técnicos:
   ritmo/groove, rango BPM, arreglo, espacio y producción.
   ============================================================ */

export type DrumStyle =
  | "none" | "rock" | "jazz" | "electro" | "march" | "latin" | "waltz"
  | "house" | "dembow" | "hiphop" | "afro" | "kpop" | "jpop" | "cumbia"
  | "bossa" | "blues" | "soul" | "balkan" | "onedrop";

export type BassStyle =
  | "sustain" | "walk" | "pulse" | "tumbao" | "oompah" | "waltz" | "eighths"
  | "dembow" | "boom" | "habanera" | "cumbia" | "logdrum" | "bossa" | "bachata" | "onedrop";

export type CompStyle =
  | "sustain" | "stab" | "comp" | "arpeggio" | "offbeat" | "waltz"
  | "montuno" | "batida" | "skank" | "sixteenth" | "rasgueado";

export interface GenreDef {
  id: string;
  nameES: string; nameEN: string;
  category: string;
  regionES: string; regionEN: string;
  blurbES: string; blurbEN: string;
  /* tabla de parámetros técnicos */
  grooveES: string; grooveEN: string;
  bpmMin: number; bpmMax: number; bpm: number;
  arrangementES: string; arrangementEN: string;
  spaceES: string; spaceEN: string;
  productionES: string; productionEN: string;
  /* datos de síntesis */
  palette: [string, string, string];
  lineup: string[];
  meter: 2 | 3 | 4;
  swing: number;
  drums: DrumStyle;
  bassStyle: BassStyle;
  compStyle: CompStyle;
  seventh: boolean;
  energy: number;
}

const G = (g: Omit<GenreDef, "bpm"> & { bpm?: number }): GenreDef => ({
  ...g,
  bpm: g.bpm ?? Math.round((g.bpmMin + g.bpmMax) / 2),
});

export const GENRES: GenreDef[] = [
  /* ============ POP Y COMERCIAL ============ */
  G({ id: "pop", nameES: "Pop Contemporáneo", nameEN: "Contemporary Pop", category: "pop",
    regionES: "Global", regionEN: "Global",
    blurbES: "Música comercial de gran difusión, melodías accesibles y producción pulida.",
    blurbEN: "Mass-market commercial music with accessible melodies and polished production.",
    grooveES: "Constante, comercial, pulido", grooveEN: "Steady, commercial, polished",
    bpmMin: 115, bpmMax: 128,
    arrangementES: "Pianos eléctricos, coros virtuales, percusión auxiliar",
    arrangementEN: "Electric pianos, virtual choir layers, auxiliary percussion",
    spaceES: "Mezcla amplia, estéreo definido, compresión limpia",
    spaceEN: "Wide mix, defined stereo, clean compression",
    productionES: "Brillante, pulida, compresión multibanda moderna",
    productionEN: "Bright, polished, modern multiband compression",
    palette: ["#ff5ca8", "#45e0cd", "#ffd28a"],
    lineup: ["synthlead", "synthpad", "synthbass", "drumkit", "eguitar", "nylon", "soprano"],
    meter: 4, swing: 0, drums: "rock", bassStyle: "eighths", compStyle: "comp", seventh: false, energy: 0.72 }),
  G({ id: "dancepop", nameES: "Dance-Pop", nameEN: "Dance-Pop", category: "pop",
    regionES: "Global", regionEN: "Global",
    blurbES: "Fusión de pop y electrónica orientada a las pistas de baile.",
    blurbEN: "Pop and electronic fusion aimed at the dance floor.",
    grooveES: "Four-on-the-floor, bailable", grooveEN: "Four-on-the-floor, danceable",
    bpmMin: 120, bpmMax: 130,
    arrangementES: "Arpegios de sintetizador, risers, bajos con sidechain",
    arrangementEN: "Synth arpeggios, risers, sidechained basses",
    spaceES: "Envolvente, optimizada para discotecas", spaceEN: "Immersive, club-optimized",
    productionES: "Alta compresión, agudos cristalinos, pegada contundente",
    productionEN: "Heavy compression, crystal highs, punchy attack",
    palette: ["#45e0cd", "#b58cff", "#ff5ca8"],
    lineup: ["drumkit", "synthbass", "synthlead", "synthpad", "epiano", "soprano"],
    meter: 4, swing: 0, drums: "house", bassStyle: "dembow", compStyle: "offbeat", seventh: false, energy: 0.78 }),

  /* ============ ROCK Y METAL ============ */
  G({ id: "rock", nameES: "Rock Clásico / Hard Rock", nameEN: "Classic / Hard Rock", category: "rock",
    regionES: "Angloamérica", regionEN: "Anglo-American",
    blurbES: "Guitarras eléctricas y bases rítmicas potentes de mediados del siglo XX.",
    blurbEN: "Electric guitars and powerful rhythm sections born in the mid-20th century.",
    grooveES: "Orgánico, pesado, directo", grooveEN: "Organic, heavy, direct",
    bpmMin: 100, bpmMax: 135,
    arrangementES: "Panderetas, guitarras dobladas, órgano Hammond de fondo",
    arrangementEN: "Tambourines, double rhythm guitars, background Hammond organ",
    spaceES: "Sala amplia, natural, eco de válvulas", spaceEN: "Wide natural hall, valve echo",
    productionES: "Analógica cálida, saturación de amplificador a tubos",
    productionEN: "Warm analog, tube-amp saturation",
    palette: ["#ff6b3d", "#ff5c5c", "#ffd28a"],
    lineup: ["eguitar", "ebass", "drumkit", "piano", "organ", "tenor"],
    meter: 4, swing: 0, drums: "rock", bassStyle: "eighths", compStyle: "comp", seventh: false, energy: 0.8 }),
  G({ id: "metal", nameES: "Heavy Metal", nameEN: "Heavy Metal", category: "rock",
    regionES: "Global", regionEN: "Global",
    blurbES: "Guitarras distorsionadas, tempos rápidos y potencia desbordante.",
    blurbEN: "Distorted guitars, fast tempos and overwhelming power.",
    grooveES: "Rápido, contundente, doble bombo", grooveEN: "Fast, punchy, double kick",
    bpmMin: 140, bpmMax: 200,
    arrangementES: "Armonías de guitarra a doble velocidad, coros épicos",
    arrangementEN: "Double-speed guitar harmonies, epic backing choirs",
    spaceES: "Estadio o sala oscura y densa", spaceEN: "Stadium or dark, dense hall",
    productionES: "Distorsión masiva, baterías ultra-cuantizadas, alta definición",
    productionEN: "Massive distortion, ultra-quantized drums, high definition",
    palette: ["#e5484d", "#8b93a7", "#ffb03a"],
    lineup: ["eguitar", "ebass", "drumkit", "tenor"],
    meter: 4, swing: 0, drums: "rock", bassStyle: "pulse", compStyle: "comp", seventh: false, energy: 0.9 }),
  G({ id: "indie", nameES: "Indie / Alternative Rock", nameEN: "Indie / Alternative Rock", category: "rock",
    regionES: "Europa / UK", regionEN: "Europe / UK",
    blurbES: "Enfoque independiente, experimentación sonora y letras introspectivas.",
    blurbEN: "Independent approach, sonic experimentation and introspective lyrics.",
    grooveES: "Orgánico, sincopado o flotante", grooveEN: "Organic, syncopated or floating",
    bpmMin: 110, bpmMax: 125,
    arrangementES: "Pandereta, guitarras con chorus/delay, bajo melódico",
    arrangementEN: "Tambourine, chorus/delay guitars, melodic bass",
    spaceES: "Íntimo pero expansivo, reverberación de placa",
    spaceEN: "Intimate yet expansive, plate reverb",
    productionES: "Lo-fi sutil o mezcla balanceada con imperfecciones humanas",
    productionEN: "Subtle lo-fi or balanced mix with human imperfections",
    palette: ["#5fd68a", "#e8c468", "#b58cff"],
    lineup: ["eguitar", "ebass", "drumkit", "synthpad", "tenor"],
    meter: 4, swing: 0, drums: "rock", bassStyle: "eighths", compStyle: "arpeggio", seventh: false, energy: 0.66 }),

  /* ============ URBANO Y ELECTRÓNICA ============ */
  G({ id: "reggaeton", nameES: "Reggaetón", nameEN: "Reggaeton", category: "urban",
    regionES: "Puerto Rico / Panamá", regionEN: "Puerto Rico / Panama",
    blurbES: "Ritmo urbano bailable con base dembow.",
    blurbEN: "Danceable urban rhythm built on the dembow.",
    grooveES: "Dembow continuo, cadencioso", grooveEN: "Continuous dembow, cadenced",
    bpmMin: 90, bpmMax: 100,
    arrangementES: "Campanas electrónicas, sintetizadores graves, efectos urbanos",
    arrangementEN: "Electronic bells, deep synths, urban FX",
    spaceES: "Seco, directo, sub-graves enfocados", spaceEN: "Dry, direct, focused sub-bass",
    productionES: "Punchy, compresión rítmica marcada, diseño sonoro urbano",
    productionEN: "Punchy, marked rhythmic compression, urban sound design",
    palette: ["#ff6b3d", "#ffd23d", "#45e0cd"],
    lineup: ["drumkit", "synthbass", "synthlead", "synthpad", "tenor"],
    meter: 4, swing: 0.08, drums: "dembow", bassStyle: "dembow", compStyle: "offbeat", seventh: false, energy: 0.74 }),
  G({ id: "hiphop", nameES: "Hip-Hop / Rap", nameEN: "Hip-Hop / Rap", category: "urban",
    regionES: "Norteamérica", regionEN: "North America",
    blurbES: "Música rítmica hablada sobre bases instrumentales y samples.",
    blurbEN: "Rhythmic spoken music over instrumental beats and samples.",
    grooveES: "Groove marcado, pesado en la caja", grooveEN: "Marked groove, snare-heavy",
    bpmMin: 75, bpmMax: 95,
    arrangementES: "Samples de vinilo, vientos sintéticos, piano melancólico",
    arrangementEN: "Vinyl samples, synth horns, melancholic piano",
    spaceES: "Sala seca (dead room), enfoque frontal", spaceEN: "Dead room, frontal focus",
    productionES: "Crujido de vinilo, compresión pesada en la batería",
    productionEN: "Vinyl crackle, heavy drum compression",
    palette: ["#e3b341", "#7c6cff", "#ff5c5c"],
    lineup: ["drumkit", "synthbass", "epiano", "synthpad", "tenor"],
    meter: 4, swing: 0.16, drums: "hiphop", bassStyle: "boom", compStyle: "stab", seventh: true, energy: 0.6 }),
  G({ id: "electro", nameES: "EDM (Electronic Dance)", nameEN: "EDM (Electronic Dance)", category: "urban",
    regionES: "Global / Europa", regionEN: "Global / Europe",
    blurbES: "Música electrónica creada para festivales y discotecas.",
    blurbEN: "Electronic music created for festivals and clubs.",
    grooveES: "Progresivo con clímax (drop)", grooveEN: "Progressive with drop climax",
    bpmMin: 126, bpmMax: 132,
    arrangementES: "Sintetizadores hipercomprimidos, ruido blanco, risers",
    arrangementEN: "Hyper-compressed synths, white noise FX, risers",
    spaceES: "Masivo, gigante, espacialidad digital de festival",
    spaceEN: "Massive, giant, festival-scale digital space",
    productionES: "Masterización ruidosa y brillante, limitación extrema",
    productionEN: "Loud, bright mastering, extreme limiting",
    palette: ["#2dd4bf", "#45e0cd", "#b58cff"],
    lineup: ["synthlead", "synthpad", "synthbass", "drumkit", "epiano"],
    meter: 4, swing: 0, drums: "electro", bassStyle: "pulse", compStyle: "arpeggio", seventh: false, energy: 0.8 }),
  G({ id: "techno", nameES: "Techno / House", nameEN: "Techno / House", category: "urban",
    regionES: "Europa / Global", regionEN: "Europe / Global",
    blurbES: "Subgéneros electrónicos de percusión repetitiva y estética de club.",
    blurbEN: "Electronic subgenres of repetitive percussion and club aesthetics.",
    grooveES: "Hipnótico, repetitivo, percusivo", grooveEN: "Hypnotic, repetitive, percussive",
    bpmMin: 120, bpmMax: 128,
    arrangementES: "Plucks minimalistas, acordes de piano de 4 tiempos",
    arrangementEN: "Minimalist plucks, four-on-the-floor piano chords",
    spaceES: "Profundo, club reverb subterráneo", spaceEN: "Deep, underground club reverb",
    productionES: "Saturación cálida, groove analógico, medios sin comprimir",
    productionEN: "Warm saturation, analog groove, uncompressed mids",
    palette: ["#35c9dd", "#9aa0b5", "#ff5ca8"],
    lineup: ["drumkit", "synthbass", "synthlead", "synthpad"],
    meter: 4, swing: 0, drums: "house", bassStyle: "logdrum", compStyle: "offbeat", seventh: false, energy: 0.76 }),

  /* ============ RITMOS LATINOS Y ANDINOS ============ */
  G({ id: "valscriollo", nameES: "Criolla / Vals Peruano", nameEN: "Criolla / Peruvian Waltz", category: "andina",
    regionES: "Perú (Costa)", regionEN: "Peru (Coast)",
    blurbES: "Género costeño que fusiona influencias españolas, africanas e indígenas.",
    blurbEN: "Coastal genre fusing Spanish, African and Indigenous influences.",
    grooveES: "Ternario elegante, compás 3/4 criollo", grooveEN: "Elegant triple feel, criollo 3/4",
    bpmMin: 70, bpmMax: 90,
    arrangementES: "Castañuelas, cajón sutil, segunda guitarra de contrapunto",
    arrangementEN: "Castanets, subtle cajón, counterpoint second guitar",
    spaceES: "Acústica de peña tradicional, calidez cercana",
    spaceEN: "Traditional peña acoustics, close warmth",
    productionES: "Limpia, acústica natural, sin estridencias digitales",
    productionEN: "Clean, natural acoustics, no digital harshness",
    palette: ["#e8c468", "#c9803a", "#8b93a7"],
    lineup: ["nylon", "cajon", "castanets", "contrabass", "quijada", "tenor", "soprano"],
    meter: 3, swing: 0.04, drums: "none", bassStyle: "waltz", compStyle: "waltz", seventh: false, energy: 0.55 }),
  G({ id: "festejo", nameES: "Festejo y Landó", nameEN: "Festejo & Landó", category: "andina",
    regionES: "Perú (Costa afroperuana)", regionEN: "Peru (Afro-Peruvian Coast)",
    blurbES: "Ritmos afroperuanos alegres, de percusión intensa y zapateo.",
    blurbEN: "Joyful Afro-Peruvian rhythms with intense percussion and zapateo.",
    grooveES: "Polirítmico, afroperuano, sincopado", grooveEN: "Polyrhythmic, Afro-Peruvian, syncopated",
    bpmMin: 95, bpmMax: 110,
    arrangementES: "Quijada de burro, cajita rítmica, palmas en vivo",
    arrangementEN: "Jawbone, cajita, live clapping palmas",
    spaceES: "Abierto, dinámico, resonancia de madera peruana",
    spaceEN: "Open, dynamic, Peruvian wood resonance",
    productionES: "Orgánica, separación estéreo de percusiones",
    productionEN: "Organic, stereo-separated percussion",
    palette: ["#ff8c42", "#e3b341", "#67c6b0"],
    lineup: ["cajon", "quijada", "cajita", "congas", "nylon", "tenor", "soprano"],
    meter: 2, swing: 0.1, drums: "none", bassStyle: "eighths", compStyle: "arpeggio", seventh: false, energy: 0.72 }),
  G({ id: "andina", nameES: "Andina (Huayno / Yaraví / Sikuri)", nameEN: "Andean (Huayno / Yaraví / Sikuri)", category: "andina",
    regionES: "Andes (Perú, Bolivia, Ecuador)", regionEN: "Andes (Peru, Bolivia, Ecuador)",
    blurbES: "Expresión milenaria: danzas festivas y lamentos profundos.",
    blurbEN: "Millennial expression: festive dances and deep laments.",
    grooveES: "Huayno alegre o yaraví melancólico", grooveEN: "Joyful huayno or melancholic yaraví",
    bpmMin: 80, bpmMax: 120,
    arrangementES: "Charango rasgueado, arpa andina, bombo legüero",
    arrangementEN: "Strummed charango, Andean harp, bombo legüero",
    spaceES: "Altiplano abierto, reverberación natural de montaña",
    spaceEN: "Open altiplano, natural mountain reverb",
    productionES: "Dinámica viva, balance acústico tradicional",
    productionEN: "Live dynamics, traditional acoustic balance",
    palette: ["#5ec8e8", "#ffd23d", "#e5484d"],
    lineup: ["zampona", "quena", "charango", "harpandes", "leguero", "tenor", "soprano"],
    meter: 2, swing: 0, drums: "none", bassStyle: "sustain", compStyle: "arpeggio", seventh: false, energy: 0.6 }),
  G({ id: "chicha", nameES: "Cumbia Amazónica (Chicha)", nameEN: "Amazonian Cumbia (Chicha)", category: "andina",
    regionES: "Perú (Selva)", regionEN: "Peru (Jungle)",
    blurbES: "Cumbia con huayno andino y psicodelia rockera de la selva.",
    blurbEN: "Cumbia meets Andean huayno and jungle rock psychedelia.",
    grooveES: "Tropical sabrosón, psicodélico", grooveEN: "Tasty tropical, psychedelic",
    bpmMin: 100, bpmMax: 115,
    arrangementES: "Guitarras con trémolo y eco, güiro, teclados compactos",
    arrangementEN: "Tremolo-and-echo guitars, güiro, compact keyboards",
    spaceES: "Psicodélica, eco de cinta analógica (tape delay)",
    spaceEN: "Psychedelic, analog tape delay",
    productionES: "Textura vintage, compresión ligera de los 70",
    productionEN: "Vintage texture, light 70s compression",
    palette: ["#63e6a4", "#ff5ca8", "#ffd23d"],
    lineup: ["eguitar", "ebass", "timbales", "congas", "guira", "tenor"],
    meter: 4, swing: 0.06, drums: "none", bassStyle: "eighths", compStyle: "arpeggio", seventh: false, energy: 0.66 }),

  /* ============ CARIBE Y SUDAMÉRICA ============ */
  G({ id: "vallenato", nameES: "Cumbia Colombiana y Vallenato", nameEN: "Colombian Cumbia & Vallenato", category: "caribe",
    regionES: "Colombia (Costa Caribe)", regionEN: "Colombia (Caribbean Coast)",
    blurbES: "Pilares de Colombia: cumbia costeña y vallenato narrativo de acordeón.",
    blurbEN: "Colombian pillars: coastal cumbia and narrative accordion vallenato.",
    grooveES: "Binario alegre, acordeón líder", grooveEN: "Joyful duple meter, lead accordion",
    bpmMin: 100, bpmMax: 112,
    arrangementES: "Acordeón diatónico, guacharaca, caja vallenata, llamador",
    arrangementEN: "Diatonic accordion, guacharaca, vallenato caja, llamador",
    spaceES: "Fiesta al aire libre, cálida, sin exceso de efectos",
    spaceEN: "Open-air fiesta, warm, minimal effects",
    productionES: "Limpia, orgánica, festiva y bailable",
    productionEN: "Clean, organic, festive and danceable",
    palette: ["#ffd23d", "#56c271", "#e5484d"],
    lineup: ["accordion", "cajavallenata", "guiro", "gaitacolo", "congas", "ebass", "tenor", "soprano"],
    meter: 4, swing: 0.08, drums: "none", bassStyle: "cumbia", compStyle: "offbeat", seventh: false, energy: 0.68 }),
  G({ id: "champeta", nameES: "Champeta y Porro", nameEN: "Champeta & Porro", category: "caribe",
    regionES: "Colombia (Caribe / Urbana)", regionEN: "Colombia (Caribbean / Urban)",
    blurbES: "Champeta de influencia africana y el alegre porro de bandas de viento.",
    blurbEN: "African-influenced champeta and the joyful wind-band porro.",
    grooveES: "Africano acelerado, bajo hiperactivo", grooveEN: "Accelerated African, hyperactive bass",
    bpmMin: 110, bpmMax: 125,
    arrangementES: "Guitarras soukous, sintetizadores tropicales / trompetas y clarinetes",
    arrangementEN: "Soukous guitars, tropical synths / trumpets and clarinets",
    spaceES: "Vibrante, denso, pegada rítmica ruda",
    spaceEN: "Vibrant, dense, rough rhythmic punch",
    productionES: "Moderna, bajos presentes, mezcla bailable",
    productionEN: "Modern, bass-forward, danceable mix",
    palette: ["#e3b341", "#ff6b3d", "#45e0cd"],
    lineup: ["synthlead", "eguitar", "synthbass", "drumkit", "trumpet", "clarinet", "bassdrum", "tenor"],
    meter: 4, swing: 0.06, drums: "electro", bassStyle: "dembow", compStyle: "sixteenth", seventh: false, energy: 0.76 }),
  G({ id: "bombaplena", nameES: "Bomba y Plena", nameEN: "Bomba & Plena", category: "caribe",
    regionES: "Puerto Rico", regionEN: "Puerto Rico",
    blurbES: "Géneros afropuertorriqueños de percusión potente y temática social.",
    blurbEN: "Afro-Puerto Rican genres of powerful drums and social themes.",
    grooveES: "Barriles de bomba, repique", grooveEN: "Bomba barrels, repique",
    bpmMin: 95, bpmMax: 110,
    arrangementES: "Pleneras, cuá, claves rítmicas, cuatro",
    arrangementEN: "Pleneras, cuá, rhythmic claves, cuatro",
    spaceES: "Acústica de calle o plaza caribeña",
    spaceEN: "Street or Caribbean square acoustics",
    productionES: "Orgánica, dinámica alta, percusión al frente",
    productionEN: "Organic, high dynamics, percussion up front",
    palette: ["#c9803a", "#e5484d", "#ffd28a"],
    lineup: ["bomba", "shaker", "cuatro", "congas", "guiro", "tenor", "soprano"],
    meter: 4, swing: 0.1, drums: "none", bassStyle: "habanera", compStyle: "offbeat", seventh: false, energy: 0.62 }),
  G({ id: "salsapr", nameES: "Salsa PR / Trova", nameEN: "PR Salsa / Trova", category: "caribe",
    regionES: "Puerto Rico", regionEN: "Puerto Rico",
    blurbES: "La escuela salsera boricua y la trova de juglares con el cuatro.",
    blurbEN: "The Puerto Rican salsa school and troubadour trova with the cuatro.",
    grooveES: "Clave 2-3 o 3-2, montuno enérgico", grooveEN: "2-3 or 3-2 clave, energetic montuno",
    bpmMin: 90, bpmMax: 105,
    arrangementES: "Piano montuno, congas, timbales, metales",
    arrangementEN: "Montuno piano, congas, timbales, brass section",
    spaceES: "Sala de baile en vivo, gran separación estéreo",
    spaceEN: "Live dance hall, wide stereo separation",
    productionES: "Rica en medios, dinámica cálida latina",
    productionEN: "Rich mids, warm Latin dynamics",
    palette: ["#5ec8e8", "#ff5c5c", "#ffd28a"],
    lineup: ["cuatro", "nylon", "congas", "timbales", "trumpet", "trombone", "ebass", "piano", "tenor"],
    meter: 4, swing: 0.1, drums: "latin", bassStyle: "tumbao", compStyle: "montuno", seventh: true, energy: 0.72 }),
  G({ id: "joropo", nameES: "Joropo Llanero y Gaita Zuliana", nameEN: "Joropo & Gaita Zuliana", category: "caribe",
    regionES: "Venezuela", regionEN: "Venezuela",
    blurbES: "Música recia de los llanos y la alegre gaita navideña del Zulia.",
    blurbEN: "Sturdy llanos music and the joyful Christmas gaita of Zulia.",
    grooveES: "Recio, zapateado rápido, arpa veloz", grooveEN: "Sturdy, fast zapateado, swift harp",
    bpmMin: 180, bpmMax: 220,
    arrangementES: "Arpa llanera, cuatro, furruco, maracas",
    arrangementEN: "Llanera harp, cuatro, furruco, maracas",
    spaceES: "Abierto, llanero, acústico y expansivo",
    spaceEN: "Open, llanos-style, acoustic and expansive",
    productionES: "Transitorios veloces, energía rústica controlada",
    productionEN: "Fast transients, controlled rustic energy",
    palette: ["#f2a06b", "#5ec8e8", "#e3b341"],
    lineup: ["harpllanera", "cuatro", "shaker", "ebass", "furruco", "guira", "tambora", "tenor"],
    meter: 3, swing: 0, drums: "none", bassStyle: "waltz", compStyle: "waltz", seventh: false, energy: 0.78 }),

  /* ============ RITMOS LATINOS ============ */
  G({ id: "latin", nameES: "Salsa", nameEN: "Salsa", category: "latin",
    regionES: "Caribe / Cuba · NY", regionEN: "Caribbean / Cuba · NY",
    blurbES: "Fusión de ritmos cubanos y jazz afroamericano nacida en Nueva York.",
    blurbEN: "Fusion of Cuban rhythms and African-American jazz born in New York.",
    grooveES: "Sincopado, clave estricta, bailable", grooveEN: "Syncopated, strict clave, danceable",
    bpmMin: 90, bpmMax: 110,
    arrangementES: "Congas, bongós, timbal, piano tumbao, bronces",
    arrangementEN: "Congas, bongos, timbal, tumbao piano, brass",
    spaceES: "Amplio, espacialidad de salón de salsa",
    spaceEN: "Wide, salsa-hall spatiality",
    productionES: "Rica en detalles percusivos, mezcla brillante",
    productionEN: "Rich percussive detail, bright mix",
    palette: ["#ff8a5c", "#ffc53d", "#ff5c5c"],
    lineup: ["piano", "ebass", "congas", "timbales", "trumpet", "trombone", "shaker", "claves", "tenor"],
    meter: 4, swing: 0.1, drums: "latin", bassStyle: "tumbao", compStyle: "montuno", seventh: true, energy: 0.74 }),
  G({ id: "bachata", nameES: "Bachata", nameEN: "Bachata", category: "latin",
    regionES: "República Dominicana", regionEN: "Dominican Republic",
    blurbES: "Género romántico y rítmico de origen caribeño.",
    blurbEN: "Romantic, rhythmic genre of Caribbean origin.",
    grooveES: "Romántico, sincopado de requinto", grooveEN: "Romantic, syncopated requinto",
    bpmMin: 120, bpmMax: 130,
    arrangementES: "Requinto, guitarra segunda, bongó con campana, güira",
    arrangementEN: "Requinto, second guitar, bongó with bell, güira",
    spaceES: "Íntimo, nocturno, cálido", spaceEN: "Intimate, nocturnal, warm",
    productionES: "Melodías al frente, producción limpia y emotiva",
    productionEN: "Melodies up front, clean emotional production",
    palette: ["#ef6ea8", "#a78bfa", "#ffd28a"],
    lineup: ["nylon", "nylon", "ebass", "congas", "guira", "tenor"].filter((v, i, a) => a.indexOf(v) === i),
    meter: 4, swing: 0.06, drums: "none", bassStyle: "bachata", compStyle: "arpeggio", seventh: true, energy: 0.58 }),
  G({ id: "merengue", nameES: "Merengue", nameEN: "Merengue", category: "latin",
    regionES: "República Dominicana", regionEN: "Dominican Republic",
    blurbES: "Ritmo rápido y bailable de carácter festivo.",
    blurbEN: "Fast, danceable rhythm with a festive character.",
    grooveES: "Rápido, binario, altamente enérgico", grooveEN: "Fast, duple, highly energetic",
    bpmMin: 125, bpmMax: 140,
    arrangementES: "Tambora, güira, acordeón o sección de vientos",
    arrangementEN: "Tambora, güira, accordion or horn section",
    spaceES: "Festivo, directo, brillante", spaceEN: "Festive, direct, bright",
    productionES: "Alta energía, compresión moderada para el baile",
    productionEN: "High energy, moderate compression for dancing",
    palette: ["#ffd23d", "#ff6b3d", "#45e0cd"],
    lineup: ["guira", "tambora", "accordion", "trumpet", "saxtenor", "ebass", "tenor"],
    meter: 2, swing: 0, drums: "none", bassStyle: "eighths", compStyle: "comp", seventh: false, energy: 0.84 }),
  G({ id: "tango", nameES: "Tango", nameEN: "Tango", category: "latin",
    regionES: "Argentina / Uruguay", regionEN: "Argentina / Uruguay",
    blurbES: "Raíz urbana y melancólica, de profunda expresión dramática.",
    blurbEN: "Urban, melancholic roots with deeply dramatic expression.",
    grooveES: "Rubato dramático, marcato, canyengue", grooveEN: "Dramatic rubato, marcato, canyengue",
    bpmMin: 60, bpmMax: 100,
    arrangementES: "Bandoneón melancólico, piano acústico, contrabajo arqueado",
    arrangementEN: "Melancholic bandoneón, acoustic piano, bowed double bass",
    spaceES: "Cafetín íntimo, acústica de madera noble",
    spaceEN: "Intimate cafetín, fine-wood acoustics",
    productionES: "Dinámica expresiva muy alta, mezcla limpia y directa",
    productionEN: "Very high expressive dynamics, clean direct mix",
    palette: ["#e5484d", "#8b93a7", "#ffb03a"],
    lineup: ["bandoneon", "piano", "contrabass", "violin", "tenor"],
    meter: 4, swing: 0.06, drums: "none", bassStyle: "habanera", compStyle: "stab", seventh: true, energy: 0.5 }),

  /* ============ TRADICIONAL Y REGIONAL ============ */
  G({ id: "flamenco", nameES: "Flamenco", nameEN: "Flamenco", category: "folk",
    regionES: "España (Andalucía)", regionEN: "Spain (Andalusia)",
    blurbES: "Arte andaluz basado en el cante, el toque y el baile.",
    blurbEN: "Andalusian art built on cante, toque and baile.",
    grooveES: "Compás de amalgama (12/8), compás gitano", grooveEN: "Amalgam meter (12/8), gypsy compás",
    bpmMin: 90, bpmMax: 130,
    arrangementES: "Guitarra flamenca, palmas, cajón, cante jondo",
    arrangementEN: "Flamenco guitar, palmas, cajón, cante jondo",
    spaceES: "Tablao andaluz, reverberación de madera y cercanía",
    spaceEN: "Andalusian tablao, wood reverb and closeness",
    productionES: "Orgánica, cruda, realce de uñas sobre la guitarra",
    productionEN: "Organic, raw, nail-on-strings detail",
    palette: ["#e5484d", "#ffb03a", "#efeaf5"],
    lineup: ["flamencog", "cajon", "palmas", "castanets", "tenor"],
    meter: 4, swing: 0.05, drums: "none", bassStyle: "sustain", compStyle: "rasgueado", seventh: true, energy: 0.68 }),
  G({ id: "mariachi", nameES: "Mariachi / Ranchera", nameEN: "Mariachi / Ranchera", category: "folk",
    regionES: "México", regionEN: "Mexico",
    blurbES: "Expresión tradicional mexicana de mariachis y baladas campestres.",
    blurbEN: "Traditional Mexican expression of mariachis and country ballads.",
    grooveES: "Vals (3/4) o polca (2/4)", grooveEN: "Waltz (3/4) or polka (2/4)",
    bpmMin: 80, bpmMax: 120,
    arrangementES: "Guitarrón, vihuela, trompetas mariachis, violines",
    arrangementEN: "Guitarrón, vihuela, mariachi trumpets, violins",
    spaceES: "Amplio, festivo, acústica de plaza", spaceEN: "Wide, festive, town-square acoustics",
    productionES: "Calidez vocal e instrumental, sin saturación",
    productionEN: "Vocal and instrumental warmth, no saturation",
    palette: ["#56c271", "#e3b341", "#e5484d"],
    lineup: ["guitarron", "vihuela", "nylon", "violin", "trumpet", "tenor"],
    meter: 3, swing: 0, drums: "none", bassStyle: "waltz", compStyle: "waltz", seventh: false, energy: 0.66 }),
  G({ id: "bossa", nameES: "Bossa Nova / Samba", nameEN: "Bossa Nova / Samba", category: "folk",
    regionES: "Brasil", regionEN: "Brazil",
    blurbES: "Fusión elegante de samba y jazz con armonías sofisticadas.",
    blurbEN: "Elegant fusion of samba and jazz with sophisticated harmonies.",
    grooveES: "Sincopado, suave, balance bossoide", grooveEN: "Syncopated, soft, bossa balance",
    bpmMin: 60, bpmMax: 90,
    arrangementES: "Nylon con acordes complejos, pandeiro, percusión ligera",
    arrangementEN: "Nylon with complex chords, pandeiro, light percussion",
    spaceES: "Íntimo, atmósfera de café costero", spaceEN: "Intimate, seaside café atmosphere",
    productionES: "Cálida, suave, compresión baja, espacio natural",
    productionEN: "Warm, soft, low compression, natural space",
    palette: ["#67c6b0", "#e8c468", "#ff9ecb"],
    lineup: ["nylon", "epiano", "contrabass", "drumkit", "shaker", "soprano"],
    meter: 4, swing: 0.18, drums: "bossa", bassStyle: "bossa", compStyle: "batida", seventh: true, energy: 0.45 }),

  /* ============ RAÍZ Y AFROAMERICANO ============ */
  G({ id: "jazz", nameES: "Jazz", nameEN: "Jazz", category: "roots",
    regionES: "Estados Unidos", regionEN: "United States",
    blurbES: "Improvisación, síncopa y expresividad instrumental.",
    blurbEN: "Improvisation, syncopation and instrumental expressiveness.",
    grooveES: "Swing, polirrítmico, improvisado", grooveEN: "Swing, polyrhythmic, improvised",
    bpmMin: 80, bpmMax: 160,
    arrangementES: "Contrabajo walking, batería con escobillas, saxofón",
    arrangementEN: "Walking double bass, brush drums, saxophone",
    spaceES: "Club de jazz (Blue Note), acústica natural y viva",
    spaceEN: "Jazz club (Blue Note), natural live acoustics",
    productionES: "Dinámica sin compresión excesiva, naturalidad extrema",
    productionEN: "Uncompressed dynamics, extreme naturalness",
    palette: ["#45e0cd", "#ffb03a", "#8b6ff0"],
    lineup: ["piano", "contrabass", "drumkit", "saxtenor", "trumpet", "eguitar"],
    meter: 4, swing: 0.24, drums: "jazz", bassStyle: "walk", compStyle: "offbeat", seventh: true, energy: 0.55 }),
  G({ id: "blues", nameES: "Blues", nameEN: "Blues", category: "roots",
    regionES: "Estados Unidos", regionEN: "United States",
    blurbES: "Notas de blues y estructuras de 12 compases.",
    blurbEN: "Blue notes and 12-bar structures.",
    grooveES: "Shuffle, lento o caminante", grooveEN: "Shuffle, slow or walking",
    bpmMin: 60, bpmMax: 110,
    arrangementES: "Guitarra con slide, armónica, piano boogie-woogie",
    arrangementEN: "Slide guitar, harmonica, boogie-woogie piano",
    spaceES: "Rústico, profundo, atmósfera de bar de blues",
    spaceEN: "Rustic, deep, blues-bar atmosphere",
    productionES: "Saturación valvular leve, sonido crudo y desgarrador",
    productionEN: "Mild tube saturation, raw tearing tone",
    palette: ["#5b7cfa", "#ffb03a", "#ff5c5c"],
    lineup: ["eguitar", "harmonica", "ebass", "drumkit", "epiano", "tenor"],
    meter: 4, swing: 0.33, drums: "blues", bassStyle: "walk", compStyle: "comp", seventh: true, energy: 0.52 }),
  G({ id: "soul", nameES: "Soul / R&B", nameEN: "Soul / R&B", category: "roots",
    regionES: "Estados Unidos", regionEN: "United States",
    blurbES: "Góspel, rhythm and blues y jazz con alta carga emocional.",
    blurbEN: "Gospel, rhythm and blues and jazz with high emotional charge.",
    grooveES: "Groove profundo, contratiempos marcados", grooveEN: "Deep groove, marked off-beats",
    bpmMin: 70, bpmMax: 100,
    arrangementES: "Órgano Hammond, vientos suaves, bajo melódico",
    arrangementEN: "Hammond organ, soft horns, melodic bass",
    spaceES: "Cálido, atmosférico, reverberación clásica de estudio",
    spaceEN: "Warm, atmospheric, classic studio reverb",
    productionES: "Textura analógica rica, voces aterciopeladas al frente",
    productionEN: "Rich analog texture, velvet vocals up front",
    palette: ["#e3b341", "#e5484d", "#b58cff"],
    lineup: ["epiano", "organ", "saxtenor", "trumpet", "trombone", "ebass", "drumkit", "tenor", "soprano"],
    meter: 4, swing: 0.1, drums: "soul", bassStyle: "walk", compStyle: "comp", seventh: true, energy: 0.6 }),
  G({ id: "reggae", nameES: "Reggae / Ska", nameEN: "Reggae / Ska", category: "roots",
    regionES: "Jamaica", regionEN: "Jamaica",
    blurbES: "Acento en los tiempos débiles y mensajes sociales.",
    blurbEN: "Off-beat accents with social messages.",
    grooveES: "Skank en contratiempo, relajado", grooveEN: "Off-beat skank, relaxed",
    bpmMin: 75, bpmMax: 140,
    arrangementES: "Bajo pesado y profundo, guitarra a contrapulso, órgano",
    arrangementEN: "Heavy deep bass, off-beat rhythm guitar, organ",
    spaceES: "Espacial, eco de cinta y reverberación de muelles",
    spaceEN: "Spatial, tape echo and spring reverb",
    productionES: "Graves masivos, agudos limpios, atmósfera jamaiquina",
    productionEN: "Massive lows, clean highs, Jamaican atmosphere",
    palette: ["#56c271", "#ffd23d", "#e5484d"],
    lineup: ["eguitar", "ebass", "drumkit", "organ", "saxtenor", "trumpet", "tenor"],
    meter: 4, swing: 0.1, drums: "onedrop", bassStyle: "onedrop", compStyle: "skank", seventh: true, energy: 0.5 }),

  /* ============ MÚSICA AFRICANA ============ */
  G({ id: "afrobeats", nameES: "Afrobeats", nameEN: "Afrobeats", category: "africa",
    regionES: "Nigeria / Ghana", regionEN: "Nigeria / Ghana",
    blurbES: "Tradición africana, highlife, jazz y funk con bases modernas.",
    blurbEN: "African tradition, highlife, jazz and funk with modern beats.",
    grooveES: "Batería africana sincopada, groove fluido", grooveEN: "Syncopated African drums, fluid groove",
    bpmMin: 100, bpmMax: 115,
    arrangementES: "Percusiones africanas, guitarras rítmicas, pads modernos",
    arrangementEN: "African percussion, rhythmic guitars, modern pads",
    spaceES: "Caluroso, envolvente, estéreo dinámico",
    spaceEN: "Warm, enveloping, dynamic stereo",
    productionES: "Ultralimpia, bajos profundos y rítmicos",
    productionEN: "Ultra-clean, deep rhythmic basses",
    palette: ["#ff8c42", "#56c271", "#ffd23d"],
    lineup: ["drumkit", "synthbass", "synthpad", "eguitar", "congas", "djembe", "tenor", "soprano"],
    meter: 4, swing: 0.12, drums: "afro", bassStyle: "dembow", compStyle: "sixteenth", seventh: true, energy: 0.72 }),
  G({ id: "mandinga", nameES: "Mandinga / Desert Blues", nameEN: "Manding / Desert Blues", category: "africa",
    regionES: "Malí / Senegal", regionEN: "Mali / Senegal",
    blurbES: "Raíz ancestral con guitarras hipnóticas y lírica profunda.",
    blurbEN: "Ancestral roots with hypnotic guitars and deep lyricism.",
    grooveES: "Hipnótico, circular, desértico", grooveEN: "Hypnotic, circular, desertic",
    bpmMin: 85, bpmMax: 110,
    arrangementES: "Kora, ngoni, guitarras con escalas modales africanas",
    arrangementEN: "Kora, ngoni, guitars in African modal scales",
    spaceES: "Desierto abierto, eco natural", spaceEN: "Open desert, natural echo",
    productionES: "Orgánica, hipnótica, baja compresión digital",
    productionEN: "Organic, hypnotic, low digital compression",
    palette: ["#e8c468", "#c9803a", "#67c6b0"],
    lineup: ["kora", "ngoni", "nylon", "shaker", "djembe", "soprano", "tenor"],
    meter: 4, swing: 0.22, drums: "none", bassStyle: "walk", compStyle: "arpeggio", seventh: false, energy: 0.5 }),
  G({ id: "soukous", nameES: "Soukous / Rumba Congoleña", nameEN: "Soukous / Congolese Rumba", category: "africa",
    regionES: "R.D. del Congo", regionEN: "DR Congo",
    blurbES: "Guitarras eléctricas intrincadas y melodías alegres (seben).",
    blurbEN: "Intricate electric guitars and joyful melodies (seben).",
    grooveES: "Ágil, guitarras entrelazadas", grooveEN: "Agile, interlocking guitars",
    bpmMin: 110, bpmMax: 130,
    arrangementES: "Guitarras gemelas veloces, bajo rítmico, percusión africana",
    arrangementEN: "Fast twin guitars, rhythmic bass, African percussion",
    spaceES: "Alegre, festivo, salón congoleño vibrante",
    spaceEN: "Joyful, festive, vibrant Congolese hall",
    productionES: "Limpia y cristalina para las guitarras gemelas",
    productionEN: "Clean and crystalline for the twin guitars",
    palette: ["#ffd23d", "#ff5ca8", "#45e0cd"],
    lineup: ["eguitar", "ebass", "drumkit", "trumpet", "saxtenor", "congas", "tenor", "soprano"],
    meter: 4, swing: 0.08, drums: "afro", bassStyle: "eighths", compStyle: "arpeggio", seventh: false, energy: 0.78 }),
  G({ id: "amapiano", nameES: "Amapiano", nameEN: "Amapiano", category: "africa",
    regionES: "Sudáfrica", regionEN: "South Africa",
    blurbES: "House sudafricano de bajos profundos y pianos jazzísticos.",
    blurbEN: "South African house with deep basslines and jazzy pianos.",
    grooveES: "Lento, profundo, log drum característico", grooveEN: "Slow, deep, signature log drum",
    bpmMin: 110, bpmMax: 115,
    arrangementES: "Log drum profundo, teclados jazzy, acordes aireados",
    arrangementEN: "Deep log drum, jazzy keys, airy chords",
    spaceES: "Espacioso, nocturno, bajo contundente y cálido",
    spaceEN: "Spacious, nocturnal, punchy warm bass",
    productionES: "Minimalista espacial, sub-graves masivos",
    productionEN: "Spatial minimalism, massive sub-bass",
    palette: ["#35c9dd", "#b58cff", "#e3b341"],
    lineup: ["epiano", "synthbass", "drumkit", "synthpad", "shaker", "tenor"],
    meter: 4, swing: 0.1, drums: "house", bassStyle: "logdrum", compStyle: "offbeat", seventh: true, energy: 0.6 }),

  /* ============ MÚSICA ASIÁTICA ============ */
  G({ id: "kpop", nameES: "K-Pop", nameEN: "K-Pop", category: "asia",
    regionES: "Corea del Sur", regionEN: "South Korea",
    blurbES: "Pop, hip-hop, R&B y EDM con coreografías complejas.",
    blurbEN: "Pop, hip-hop, R&B and EDM with complex choreographies.",
    grooveES: "Cambiante, dinámico, multi-sección", grooveEN: "Shifting, dynamic, multi-section",
    bpmMin: 120, bpmMax: 135,
    arrangementES: "Sintetizadores futuristas, FX punzantes, orquestación pop",
    arrangementEN: "Futuristic synths, sharp FX, pop orchestration",
    spaceES: "Ultra-producido, brillante, espacialidad de estadio",
    spaceEN: "Ultra-produced, bright, stadium spatiality",
    productionES: "Masterización de volumen extremo, hiper-limpia",
    productionEN: "Extreme loudness mastering, hyper-clean",
    palette: ["#ff5ca8", "#45e0cd", "#ffd23d"],
    lineup: ["synthlead", "synthbass", "drumkit", "synthpad", "tenor", "soprano"],
    meter: 4, swing: 0.04, drums: "kpop", bassStyle: "dembow", compStyle: "stab", seventh: true, energy: 0.8 }),
  G({ id: "jpop", nameES: "J-Pop / J-Rock / Anime", nameEN: "J-Pop / J-Rock / Anime", category: "asia",
    regionES: "Japón", regionEN: "Japan",
    blurbES: "Arreglos melódicos complejos, alta energía y orquestación rica.",
    blurbEN: "Complex melodic arrangements, high energy and rich orchestration.",
    grooveES: "Rápido, enérgico, síncopas dramáticas", grooveEN: "Fast, energetic, dramatic syncopations",
    bpmMin: 130, bpmMax: 170,
    arrangementES: "Cuerdas veloces, guitarras melódicas, pianos rápidos",
    arrangementEN: "Fast strings, melodic guitars, speedy pianos",
    spaceES: "Animado, cinematográfico, brillante",
    spaceEN: "Animated, cinematic, bright",
    productionES: "Alta definición de agudos, densidad equilibrada",
    productionEN: "High-definition highs, balanced density",
    palette: ["#ff9ec4", "#45e0cd", "#ffd28a"],
    lineup: ["eguitar", "synthlead", "piano", "violin", "drumkit", "synthbass", "soprano"],
    meter: 4, swing: 0, drums: "jpop", bassStyle: "eighths", compStyle: "comp", seventh: true, energy: 0.82 }),
  G({ id: "filmi", nameES: "Indostaní / Filmi (Bollywood)", nameEN: "Hindustani / Filmi (Bollywood)", category: "asia",
    regionES: "India", regionEN: "India",
    blurbES: "Tradición milenaria de ragas y talas adaptada al cine masivo.",
    blurbEN: "Millennial tradition of ragas and talas adapted to mass cinema.",
    grooveES: "Cíclico (tala), patrones rítmicos complejos", grooveEN: "Cyclical (tala), complex rhythmic patterns",
    bpmMin: 70, bpmMax: 140,
    arrangementES: "Sitar, tabla, harmonio, flauta bansuri",
    arrangementEN: "Sitar, tabla, harmonium, bansuri flute",
    spaceES: "Meditativo o gran sala de cine (Bollywood)",
    spaceEN: "Meditative or grand cinema hall (Bollywood)",
    productionES: "Acústica natural con masterización cinematográfica",
    productionEN: "Natural acoustics with cinematic mastering",
    palette: ["#ffb03a", "#e5484d", "#67c6b0"],
    lineup: ["sitar", "tabla", "harmonium", "flute", "nylon", "synthpad", "soprano", "tenor"],
    meter: 4, swing: 0.12, drums: "none", bassStyle: "sustain", compStyle: "sustain", seventh: false, energy: 0.52 }),

  /* ============ EUROPA DEL ESTE Y BALCANES ============ */
  G({ id: "balkan", nameES: "Balcánico / Klezmer / Gipsy Brass", nameEN: "Balkan / Klezmer / Gipsy Brass", category: "east",
    regionES: "Europa Oriental / Balcanes", regionEN: "Eastern Europe / Balkans",
    blurbES: "Festiva y melancólica, con tempos acelerados y metales enérgicos.",
    blurbEN: "Festive and melancholic, with breakneck tempos and energetic brass.",
    grooveES: "Rápido, zíngaro, compases amalgamados", grooveEN: "Fast, gypsy, amalgam meters",
    bpmMin: 130, bpmMax: 160,
    arrangementES: "Clarinete expresivo, acordeón, metales, violines gitanos",
    arrangementEN: "Expressive clarinet, accordion, brass, gypsy violins",
    spaceES: "Fiesta gitana al aire libre, acústica viva",
    spaceEN: "Open-air gypsy fiesta, live acoustics",
    productionES: "Orgánica, cruda, alta energía transitoria",
    productionEN: "Organic, raw, high transient energy",
    palette: ["#e3b341", "#e5484d", "#b58cff"],
    lineup: ["trumpet", "clarinet", "accordion", "tuba", "violin", "drumkit", "tenor", "soprano"],
    meter: 2, swing: 0.04, drums: "balkan", bassStyle: "oompah", compStyle: "stab", seventh: true, energy: 0.84 }),
  G({ id: "slavic", nameES: "Folclore Eslavo / Canto Coral", nameEN: "Slavic Folk / Choral Singing", category: "east",
    regionES: "Rusia / Europa del Este", regionEN: "Russia / Eastern Europe",
    blurbES: "Voces graves profundas y cuerdas autóctonas.",
    blurbEN: "Deep low voices and native string instruments.",
    grooveES: "Solemne, marchas o cantos a capela", grooveEN: "Solemn, marches or a cappella chants",
    bpmMin: 60, bpmMax: 90,
    arrangementES: "Coros polifónicos, balalaika, acordeón cromático",
    arrangementEN: "Polyphonic choirs, balalaika, chromatic accordion",
    spaceES: "Catedral, sala de conciertos perfecta",
    spaceEN: "Cathedral, acoustically perfect concert hall",
    productionES: "Voces al frente, reverberación coral majestuosa",
    productionEN: "Vocals forward, majestic choral reverb",
    palette: ["#8b93a7", "#c9a0dc", "#e3b341"],
    lineup: ["balalaika", "accordion", "contrabass", "violin", "basso", "alto", "tenor"],
    meter: 4, swing: 0, drums: "none", bassStyle: "sustain", compStyle: "arpeggio", seventh: false, energy: 0.42 }),

  /* ============ CLÁSICA Y EUROPA ============ */
  G({ id: "symphonic", nameES: "Clásica / Sinfónica", nameEN: "Classical / Symphonic", category: "classic",
    regionES: "Europa Occidental", regionEN: "Western Europe",
    blurbES: "Tradición culta occidental, del medievo a la contemporaneidad.",
    blurbEN: "Western art-music tradition, medieval to contemporary.",
    grooveES: "Rubato variable, del pianissimo al fortissimo", grooveEN: "Variable rubato, pianissimo to fortissimo",
    bpmMin: 40, bpmMax: 180,
    arrangementES: "Orquesta completa: cuerdas, maderas, metales, percusión culta",
    arrangementEN: "Full orchestra: strings, woodwinds, brass, art percussion",
    spaceES: "Sala sinfónica (Musikverein), gran reverberación",
    spaceEN: "Symphonic hall (Musikverein), grand reverb",
    productionES: "Rango dinámico nativo, sin compresión agresiva",
    productionEN: "Native dynamic range, no aggressive compression",
    palette: ["#ffb03a", "#b58cff", "#2dd4bf"],
    lineup: ["violin", "viola", "cello", "contrabass", "flute", "clarinet", "horn", "trumpet", "trombone", "timpani", "harp"],
    meter: 4, swing: 0, drums: "none", bassStyle: "sustain", compStyle: "sustain", seventh: false, energy: 0.62 }),
  G({ id: "celtic", nameES: "Celta / Folk Europeo", nameEN: "Celtic / European Folk", category: "classic",
    regionES: "Naciones celtas / Europa Central", regionEN: "Celtic nations / Central Europe",
    blurbES: "Música tradicional de las naciones celtas y Europa central.",
    blurbEN: "Traditional music of the Celtic nations and central Europe.",
    grooveES: "Gigas y reels enérgicos, o pasajes lentos", grooveEN: "Energetic jigs and reels, or slow airs",
    bpmMin: 90, bpmMax: 130,
    arrangementES: "Tin whistle, fiddle, arpa celta, bodhrán",
    arrangementEN: "Tin whistle, fiddle, Celtic harp, bodhrán",
    spaceES: "Paisaje verde o pub irlandés, atmósfera mística",
    spaceEN: "Green landscape or Irish pub, mystic atmosphere",
    productionES: "Acústica limpia, natural y evocadora",
    productionEN: "Clean, natural, evocative acoustics",
    palette: ["#5fd68a", "#6fc3df", "#e8c468"],
    lineup: ["gaita", "violin", "flute", "harp", "accordion", "bodhran", "soprano"],
    meter: 3, swing: 0.14, drums: "none", bassStyle: "walk", compStyle: "arpeggio", seventh: false, energy: 0.62 }),

  /* ============ ESTUDIOS ADICIONALES ============ */
  G({ id: "chamber", nameES: "Música de Cámara", nameEN: "Chamber Music", category: "classic",
    regionES: "Europa Occidental", regionEN: "Western Europe",
    blurbES: "Formaciones íntimas de cuerda, viento y teclado.",
    blurbEN: "Intimate ensembles of strings, winds and keys.",
    grooveES: "Flexibilidad camerística, diálogo entre voces", grooveEN: "Chamber flexibility, dialogue between voices",
    bpmMin: 60, bpmMax: 120,
    arrangementES: "Tríos y cuartetos: cuerdas, flauta, clarinete, piano",
    arrangementEN: "Trios and quartets: strings, flute, clarinet, piano",
    spaceES: "Salón de cámara, reverberación corta y elegante",
    spaceEN: "Chamber salon, short elegant reverb",
    productionES: "Natural, transparencia de texturas",
    productionEN: "Natural, textural transparency",
    palette: ["#ffd28a", "#ff9ecb", "#7ff0e2"],
    lineup: ["violin", "cello", "flute", "clarinet", "piano", "harp"],
    meter: 4, swing: 0, drums: "none", bassStyle: "sustain", compStyle: "sustain", seventh: false, energy: 0.5 }),
  G({ id: "marching", nameES: "Banda de Marcha", nameEN: "Marching Band", category: "classic",
    regionES: "Global", regionEN: "Global",
    blurbES: "Metales, tambores y energía de desfile.",
    blurbEN: "Brass, drums and parade energy.",
    grooveES: "Marcial, binario, precisión de desfile", grooveEN: "Martial, duple, parade precision",
    bpmMin: 110, bpmMax: 126,
    arrangementES: "Metales al frente, línea de tambores, cencerros",
    arrangementEN: "Brass front, drum line, cowbells",
    spaceES: "Estadio abierto, proyección al aire libre",
    spaceEN: "Open stadium, outdoor projection",
    productionES: "Contundente, transitorios marcados",
    productionEN: "Punchy, marked transients",
    palette: ["#ffc53d", "#ff6b3d", "#efeaf5"],
    lineup: ["trumpet", "trombone", "tuba", "clarinet", "snareline", "bassdrum", "cowbell"],
    meter: 2, swing: 0, drums: "march", bassStyle: "oompah", compStyle: "stab", seventh: false, energy: 0.8 }),
  G({ id: "cinematic", nameES: "Cinemática", nameEN: "Cinematic", category: "classic",
    regionES: "Global", regionEN: "Global",
    blurbES: "Texturas híbridas para bandas sonoras.",
    blurbEN: "Hybrid textures for film scores.",
    grooveES: "Pulso de banda sonora, tensión y resolución", grooveEN: "Score pulse, tension and release",
    bpmMin: 60, bpmMax: 120,
    arrangementES: "Pads híbridos, cuerdas, metales graves, percusión épica",
    arrangementEN: "Hybrid pads, strings, low brass, epic percussion",
    spaceES: "Escenario sonoro gigante, reverberación larga",
    spaceEN: "Giant soundscape, long reverb",
    productionES: "Ancha, dramática, masterización de trailer",
    productionEN: "Wide, dramatic, trailer mastering",
    palette: ["#b58cff", "#ffb03a", "#1fa99a"],
    lineup: ["synthpad", "violin", "cello", "horn", "timpani", "synthbass", "celesta"],
    meter: 4, swing: 0, drums: "none", bassStyle: "sustain", compStyle: "sustain", seventh: false, energy: 0.58 }),
];

export const GENRE_MAP: Record<string, GenreDef> = Object.fromEntries(GENRES.map((g) => [g.id, g]));

export const genreName = (id: string, lang: "es" | "en") => {
  const g = GENRE_MAP[id];
  return g ? (lang === "es" ? g.nameES : g.nameEN) : id;
};

export const CATEGORY_ORDER = ["pop", "rock", "urban", "andina", "caribe", "latin", "folk", "roots", "africa", "asia", "east", "classic"];

export const CATEGORY_LABELS: Record<string, { es: string; en: string }> = {
  pop: { es: "Pop y Comercial", en: "Pop & Commercial" },
  rock: { es: "Rock y Metal", en: "Rock & Metal" },
  urban: { es: "Urbano y Electrónica", en: "Urban & Electronic" },
  andina: { es: "Ritmos Latinos y Andinos", en: "Latin & Andean Rhythms" },
  caribe: { es: "Caribe y Sudamérica", en: "Caribbean & South America" },
  latin: { es: "Ritmos Latinos", en: "Latin Rhythms" },
  folk: { es: "Tradicional y Regional", en: "Traditional & Regional" },
  roots: { es: "Raíz y Afroamericano", en: "Roots & African-American" },
  africa: { es: "Música Africana", en: "African Music" },
  asia: { es: "Música Asiática", en: "Asian Music" },
  east: { es: "Europa del Este y Balcanes", en: "Eastern Europe & Balkans" },
  classic: { es: "Clásica y Europa", en: "Classical & Europe" },
};

/* espacio (0..1) y brillo (0..1) derivados de la tabla de producción */
export const SPACE_BRIGHT: Record<string, [number, number]> = {
  pop: [0.55, 0.85], dancepop: [0.6, 0.9], rock: [0.55, 0.7], metal: [0.6, 0.6], indie: [0.45, 0.6],
  reggaeton: [0.25, 0.65], hiphop: [0.2, 0.5], electro: [0.8, 0.85], techno: [0.5, 0.55],
  valscriollo: [0.35, 0.6], festejo: [0.5, 0.65], andina: [0.65, 0.6], chicha: [0.45, 0.7],
  vallenato: [0.5, 0.65], champeta: [0.5, 0.6], bombaplena: [0.55, 0.6], salsapr: [0.55, 0.65], joropo: [0.6, 0.75],
  latin: [0.55, 0.7], bachata: [0.3, 0.6], merengue: [0.45, 0.8], tango: [0.35, 0.55],
  flamenco: [0.3, 0.6], mariachi: [0.55, 0.7], bossa: [0.3, 0.55],
  jazz: [0.4, 0.55], blues: [0.3, 0.5], soul: [0.45, 0.6], reggae: [0.5, 0.55],
  afrobeats: [0.55, 0.6], mandinga: [0.6, 0.55], soukous: [0.5, 0.75], amapiano: [0.55, 0.5],
  kpop: [0.8, 0.9], jpop: [0.7, 0.85], filmi: [0.6, 0.6],
  balkan: [0.5, 0.7], slavic: [0.75, 0.45],
  symphonic: [0.6, 0.7], celtic: [0.5, 0.7], chamber: [0.45, 0.65], marching: [0.4, 0.75], cinematic: [0.6, 0.7],
};

export function spaceBrightOf(genreId: string): [number, number] {
  return SPACE_BRIGHT[genreId] ?? [0.4, 0.7];
}

/* ---------- fusión de estilos ---------- */

export function fusedGenres(orch: Pick<Orchestra, "genreId" | "fusions">): GenreDef[] {
  const base = GENRE_MAP[orch.genreId] ?? GENRES[0];
  const extras = (orch.fusions ?? []).map((f) => GENRE_MAP[f]).filter(Boolean) as GenreDef[];
  return [base, ...extras];
}

export function fusedBpmRange(orch: Pick<Orchestra, "genreId" | "fusions">): [number, number] {
  const gs = fusedGenres(orch);
  const mn = Math.max(...gs.map((g) => g.bpmMin));
  const mx = Math.min(...gs.map((g) => g.bpmMax));
  return mn <= mx ? [mn, mx] : [gs[0].bpmMin, gs[0].bpmMax];
}

export function fusedLineup(orch: Pick<Orchestra, "genreId" | "fusions">): string[] {
  return [...new Set(fusedGenres(orch).flatMap((g) => g.lineup))];
}

/* ---------- distribución en el escenario ---------- */

const FAMILY_BANDS: Record<string, { y: number; spread: number; x0: number; x1: number }> = {
  keys:       { y: 0.80, spread: 0.05, x0: 0.06, x1: 0.30 },
  plucked:    { y: 0.74, spread: 0.05, x0: 0.14, x1: 0.42 },
  strings:    { y: 0.62, spread: 0.06, x0: 0.20, x1: 0.66 },
  winds:      { y: 0.44, spread: 0.04, x0: 0.30, x1: 0.72 },
  voice:      { y: 0.30, spread: 0.04, x0: 0.38, x1: 0.62 },
  brass:      { y: 0.24, spread: 0.04, x0: 0.52, x1: 0.90 },
  drums:      { y: 0.52, spread: 0.04, x0: 0.76, x1: 0.92 },
  percussion: { y: 0.36, spread: 0.04, x0: 0.72, x1: 0.94 },
  synth:      { y: 0.78, spread: 0.05, x0: 0.58, x1: 0.88 },
};

export function layoutStage(instrumentIds: string[], seedStr = "stage"): Record<string, StagePos> {
  const rng = mulberry32(hashString(seedStr));
  const groups: Record<string, string[]> = {};
  for (const id of instrumentIds) {
    const fam = INSTRUMENT_MAP[id]?.family ?? "strings";
    (groups[fam] ??= []).push(id);
  }
  const out: Record<string, StagePos> = {};
  for (const [fam, ids] of Object.entries(groups)) {
    const band = FAMILY_BANDS[fam] ?? FAMILY_BANDS.strings;
    const n = ids.length;
    ids.forEach((id, i) => {
      const t = n === 1 ? 0.5 : i / (n - 1);
      const x = band.x0 + (band.x1 - band.x0) * t + (rng() - 0.5) * band.spread;
      const y = band.y + (rng() - 0.5) * band.spread + Math.abs(t - 0.5) * 0.06;
      out[id] = { x: Math.min(0.96, Math.max(0.04, x)), y: Math.min(0.94, Math.max(0.12, y)) };
    });
  }
  return out;
}

export function defaultChannels(instrumentIds: string[], stage: Record<string, StagePos>): Record<string, ChannelState> {
  const ch: Record<string, ChannelState> = {};
  for (const id of instrumentIds) {
    const def = INSTRUMENT_MAP[id];
    const pos = stage[id] ?? { x: 0.5, y: 0.5 };
    ch[id] = {
      volume: def?.vol ?? 0.75,
      pan: Math.max(-0.85, Math.min(0.85, (pos.x - 0.5) * 1.3)),
      mute: false,
      solo: false,
    };
  }
  return ch;
}

export const defaultChannel = (id: string): ChannelState => ({
  volume: INSTRUMENT_MAP[id]?.vol ?? 0.75,
  pan: 0,
  mute: false,
  solo: false,
});

